[build]
  base    = "cms-frontend"     # Points to the subdirectory containing your Next.js project
  command = "npm run build"    # The build command
  publish = ".next"            # The directory to publish (relative to base)

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "18.16.0"     # Specify a precise, supported Node.js version
